services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: astro-todo-db
    volumes:
      - astro_todo_db_data:/data/postgres
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: astro-todo-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
      NODE_ENV: production
    ports:
      - "${APP_PORT:-8080}:8080"

volumes:
  astro_todo_db_data:
