services:
  postgres-dev:
    image: postgres:14-alpine
    container_name: postgres-dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./.env
volumes:
  postgresDB:
